# The fixture is generated by Stata 19; every option has an R replay.
read_tab_presentation <- function(path) {
    lines <- readLines(path, warn = FALSE)
    commands <- grep("^\\. ", lines)
    starts <- grep("^\\. tabulate ", lines)
    lapply(starts, function(start) {
        end <- commands[commands > start][[1L]] - 1L
        output <- lines[seq.int(start + 1L, end)]
        while (length(output) && !nzchar(output[[1L]])) output <- output[-1L]
        while (length(output) && !nzchar(output[[length(output)]])) {
            output <- output[-length(output)]
        }
        list(command = sub("^\\. ", "", lines[[start]]), output = output)
    })
}

test_that("presentation options replay Stata's output", {
    blocks <- read_tab_presentation(test_path("fixtures", "tabulate-presentation.log"))
    position <- 0L
    stata <- function(command, result, width = 80L) {
        position <<- position + 1L
        block <- blocks[[position]]
        expect_identical(block$command, command)
        expect_identical(format(result, width = width), block$output, info = command)
    }
    d <- read_dta(fixture("auto_v118.dta"))
    stata("tabulate foreign, nofreq", tab(d, foreign, nofreq = TRUE))
    stata("tabulate foreign rep78, nofreq", tab(d, foreign, rep78, nofreq = TRUE))
    stata("tabulate foreign, plot", tab(d, foreign, plot = TRUE))
    stata("tabulate foreign, plot nofreq", tab(d, foreign, plot = TRUE, nofreq = TRUE))
    stata("tabulate rep78, plot", tab(d, rep78, plot = TRUE))
    stata("tabulate foreign rep78, row nokey", tab(d, foreign, rep78, row = TRUE, nokey = TRUE))
    stata("tabulate foreign rep78, key", tab(d, foreign, rep78, key = TRUE))
    stata("tabulate foreign rep78, cchi2 clrchi2", tab(d, foreign, rep78, cchi2 = TRUE, clrchi2 = TRUE))
    stata("tabulate foreign rep78, cchi2 clrchi2 nofreq", tab(d, foreign, rep78, cchi2 = TRUE, clrchi2 = TRUE, nofreq = TRUE))
    stata("tabulate rep78 foreign, expected cchi2 clrchi2 row column cell",
          tab(d, rep78, foreign, expected = TRUE, cchi2 = TRUE, clrchi2 = TRUE,
              row = TRUE, column = TRUE, cell = TRUE))
    d$aw <- seq_len(nrow(d)) / 3
    stata("tabulate rep78 [aw=aw]", tab(d, rep78, weights = aw, weight = "aweight"))
    stata("tabulate rep78 [iw=aw]", tab(d, rep78, weights = aw, weight = "iweight"))
    stata("tabulate rep78 foreign [aw=aw], expected row column cell",
          tab(d, rep78, foreign, weights = aw, weight = "aweight", expected = TRUE,
              row = TRUE, column = TRUE, cell = TRUE))
    stata("tabulate rep78 foreign [iw=aw], expected row column cell",
          tab(d, rep78, foreign, weights = aw, weight = "iweight", expected = TRUE,
              row = TRUE, column = TRUE, cell = TRUE))
    stata("tabulate foreign, plot", tab(d[rep(seq_len(nrow(d)), 10L), ], foreign, plot = TRUE))
    big <- d[rep(seq_len(nrow(d)), 10L), ]
    set_val_labels(big, foreign, c("Domestic car made in the United States of America" = 0,
                                  "Foreign car" = 1))
    stata("tabulate foreign, plot", tab(big, foreign, plot = TRUE))
    d <- data.frame(x = c(1, 1, 2, 2, 3, 3), y = rep(1:2, 3), w = c(1.5, 2.25, .25, 3, 1, 4))
    stata("tabulate x [iw=w]", tab(d, x, weights = w, weight = "iweight"))
    stata("tabulate x y [iw=w], expected row column cell",
          tab(d, x, y, weights = w, weight = "iweight", expected = TRUE,
              row = TRUE, column = TRUE, cell = TRUE))
    stata("tabulate x [aw=w]", tab(d, x, weights = w, weight = "aweight"))
    stata("tabulate x y [aw=w], expected", tab(d, x, y, weights = w, weight = "aweight", expected = TRUE))
    # Stata's wrap disables panel splitting; the console can wrap the resulting
    # physical line, whereas format() returns the intact logical line.
    stata("tabulate y x, wrap", tab(d, y, x, wrap = TRUE), width = 30L)
    d <- data.frame(x = 1:8, w = c(1.23456789123, 21.8257197696,
        21.825719769, 2.330902111, 1.23456789012345, 123456789.12345,
        .000000123456789, 1234567890123456))
    stata("tabulate x [iw=w]", tab(d, x, weights = w, weight = "iweight"))
    d <- data.frame(x = 1:4, y = c(1, 1, 2, 2),
                    w = c(1.5, 2.5, .5, .5), s = c(1, 0, NA, 0))
    stata("tabulate x [iw=w], plot", tab(d, x, weights = w, weight = "iweight", plot = TRUE))
    stata("tabulate x y, subpop(s) row column cell expected cchi2 clrchi2 all",
          tab(d, x, y, subpop = s, row = TRUE, column = TRUE, cell = TRUE,
              expected = TRUE, cchi2 = TRUE, clrchi2 = TRUE, all = TRUE))
    d$s <- 0
    stata("tabulate x, subpop(s)", tab(d, x, subpop = s))
    stata("tabulate x, subpop(s) plot", tab(d, x, subpop = s, plot = TRUE))
    stata("tabulate x y, subpop(s) row column cell expected cchi2 clrchi2 all",
          tab(d, x, y, subpop = s, row = TRUE, column = TRUE, cell = TRUE,
              expected = TRUE, cchi2 = TRUE, clrchi2 = TRUE, all = TRUE))
    expect_identical(position, length(blocks))
    do_commands <- grep("^tabulate ", readLines(test_path("fixtures", "tabulate-presentation.do")), value = TRUE)
    expect_identical(vapply(blocks, `[[`, character(1), "command"), do_commands)
})

test_that("nofreq without cell statistics is silent and keeps the counts", {
    one <- tab(c(1, 1, 2), nofreq = TRUE)
    two <- tab(c(1, 1, 2), c(1, 2, 1), nofreq = TRUE)
    expect_identical(format(one), character())
    expect_identical(format(two), character())
    expect_output(print(one), NA)
    expect_output(print(two), NA)
    expect_equal(sum(one), 3)
    expect_equal(sum(two), 3)
})

test_that("fractional weighted frequencies survive data-frame conversion", {
    x <- tab(c(1, 1, 2), weights = c(.5, .25, 1), weight = "iweight")
    frame <- as.data.frame(x)
    expect_equal(frame$Freq, c(.75, 1))
    expect_equal(frame$percent, 100 * c(.75, 1) / 1.75)
    expect_equal(frame$cum, 100 * c(.75, 1.75) / 1.75)
})

test_that("empty nofreq output follows native one- and two-way behavior", {
    expect_identical(format(tab(NA_real_, nofreq = TRUE)), "no observations")
    expect_identical(format(tab(NA_real_, NA_real_, nofreq = TRUE)), character())
    expect_identical(format(tab(NA_real_, NA_real_, nofreq = TRUE, key = TRUE)), character())
    expect_identical(format(tab(NA_real_, NA_real_, nofreq = TRUE, chi2 = TRUE)), "no observations")
    expect_identical(format(tab(NA_real_, NA_real_, nofreq = TRUE, row = TRUE)), "no observations")
})

test_that("replacing counts or labels cannot retain stale tabulation results", {
    original <- tab(c(1, 1, 2, 2), c(1, 2, 1, 2), chi2 = TRUE,
                    collect = TRUE, matcell = TRUE)
    counts <- original
    counts[1, 1] <- 100L
    expect_s3_class(counts, "table", exact = TRUE)
    expect_null(attr(counts, "r"))
    expect_null(attr(counts, "collection"))
    expect_false(any(grepl("Pearson", format(counts))))
    expect_equal(counts[1, 1], 100)

    cell <- original
    cell[[1, 1]] <- 100L
    expect_s3_class(cell, "table", exact = TRUE)
    expect_null(attr(cell, "r"))

    missing <- original
    is.na(missing) <- c(TRUE, FALSE, FALSE, FALSE)
    expect_s3_class(missing, "table", exact = TRUE)
    expect_null(attr(missing, "r"))

    labels <- original
    dimnames(labels) <- list(c("first", "second"), c("yes", "no"))
    expect_s3_class(labels, "table", exact = TRUE)
    expect_null(attr(labels, "dta_tab"))
    expect_identical(rownames(labels), c("first", "second"))

    reshaped <- original
    dim(reshaped) <- c(4L, 1L)
    expect_s3_class(reshaped, "table", exact = TRUE)
    expect_null(attr(reshaped, "r"))
    expect_identical(dim(reshaped), c(4L, 1L))

    renamed <- tab(c(1, 1, 2))
    names(renamed) <- c("first", "second")
    expect_s3_class(renamed, "table", exact = TRUE)
    expect_null(attr(renamed, "dta_tab"))
    expect_identical(names(renamed), c("first", "second"))
})
