# Generated by conformance/stata/egen/egen.do with Stata 18.0.
egen_fixture <- function() {
    raw <- read.csv(fixture("egen_stata18.csv"), colClasses = "character",
        check.names = FALSE, na.strings = NULL, encoding = "UTF-8")
    lapply(raw, function(x) {
        if (identical(x, raw$s)) return(x)
        out <- suppressWarnings(as.double(x))
        for (tag in letters) out[x == paste0(".", tag)] <- tagged_missing(tag)
        out
    })
}

expect_egen_fixture_values <- function(actual, expected) {
    expect_equal(as.double(actual), expected, ignore_attr = TRUE)
    expect_identical(missing_tag(as.double(actual)), missing_tag(expected))
}

test_that("numeric egen values match the Stata 18 differential fixture", {
    reference <- egen_fixture()
    rows <- list(c(2, 4), c(1, 3, 9), c(5, 6), 7, 8)
    calculations <- list(mean_x = dta_mean, min_x = dta_min,
        max_x = dta_max, total_x = dta_total,
        total_missing = function(x) dta_total(x, missing = TRUE))
    for (name in names(calculations)) {
        for (index in rows) {
            actual <- calculations[[name]](reference$x[index])
            expect_egen_fixture_values(rep(actual, length(index)),
                reference[[name]][index])
        }
    }
    # Stata 18 leaks the final input's missing tag when all inputs are
    # missing. The accepted helper contract returns system missing instead.
    expected_row_max <- reference$row_max
    expected_row_max[is.na(expected_row_max)] <- NA_real_
    expect_egen_fixture_values(dta_row_max(reference$x, reference$y),
        expected_row_max)
    expect_egen_fixture_values(dta_row_total(reference$x, reference$y),
        reference$row_total)
    expect_egen_fixture_values(
        dta_row_total(reference$x, reference$y, missing = TRUE),
        reference$row_total_missing)
})

test_that("group identifiers and tags match the Stata 18 fixture", {
    reference <- egen_fixture()
    expect_egen_fixture_values(dta_group_id(reference$g, reference$s),
        reference$group_id)
    expect_egen_fixture_values(
        dta_group_id(reference$g, reference$s, missing = TRUE),
        reference$group_missing)
    expect_egen_fixture_values(dta_group_tag(reference$g, reference$s),
        reference$tag)
    expect_egen_fixture_values(
        dta_group_tag(reference$g, reference$s, missing = TRUE),
        reference$tag_missing)
})

test_that("group labels match Stata numeric formatting and Unicode truncation", {
    reference <- read.csv(fixture("egen_labels_stata18.csv"),
        stringsAsFactors = FALSE, encoding = "UTF-8")
    category <- labelled_for_test(as.double(reference$category),
        labels = c("élève" = 1, "東京語" = 2, "🙂🙂abc" = 3))
    result <- dta_group_id(number = reference$number, text = reference$text,
        category = category, label = TRUE, label_name = "unicode_codes",
        truncate = 3)
    expect_equal(as.double(result), as.double(reference$code))
    labels <- attr(result, "labels", exact = TRUE)
    expect_identical(names(labels)[match(as.double(result), unname(labels))],
        reference$label_text)
    expect_identical(attr(result, "value.label.name", exact = TRUE),
        "unicode_codes")
})

test_that("egen commands reproduce source call shapes and Stata storage", {
    reference <- egen_fixture()
    data <- dibble(obs = reference$obs, g = dta_byte(reference$g),
        x = reference$x, y = reference$y, s = reference$s,
        selected = reference$selected == 1)
    egen(data, selected_total = dta_total(x), by = g,
        where = selected, type = "double")
    egen(data, observed = dta_total(!is_missing(x)), by = g, type = "double")
    egen(data, any_observed = dta_max(!is_missing(x)), by = g, type = "byte")
    egen(data, tag_selected = dta_group_tag(g, s), where = selected)
    withr::local_options(dtatools.generate_type = "float")
    egen(data, rounded_total = dta_total(x), by = g)
    for (name in c("selected_total", "observed", "any_observed",
        "tag_selected", "rounded_total")) {
        expect_egen_fixture_values(data[[name]], reference[[name]])
    }
    expect_identical(dta_storage_type(data$any_observed), "byte")
    expect_identical(dta_storage_type(data$tag_selected), "byte")
    expect_identical(dta_storage_type(data$rounded_total), "float")
    egen(data, ordered_min = dta_min(x), bysort = g, type = "long")
    expect_egen_fixture_values(data$ordered_min[order(data$obs)],
        reference$ordered_min)
})

test_that("egen accumulation follows Stata double precision and input order", {
    reference <- read.csv(fixture("egen_precision_stata18.csv"))
    for (case in unique(reference$case)) {
        sample <- reference[reference$case == case, ]
        expect_equal(dta_total(sample$x), sample$total[[1L]], tolerance = 0)
        expect_equal(dta_mean(sample$x), sample$mean[[1L]], tolerance = 0)
        expect_equal(dta_row_total(sample$x[[1L]], sample$x[[2L]],
            sample$x[[3L]]), sample$row_total[[1L]], tolerance = 0)
    }
})

test_that("group numeric labels match Stata fixed and exponential formatting", {
    # Binary input avoids decimal CSV parsing changing exact whole doubles.
    reference <- read_dta(fixture("egen_number_labels_stata18.dta"))
    result <- dta_group_id(number = reference$number, label = TRUE)
    labels <- attr(result, "labels", exact = TRUE)
    expect_equal(as.double(result), as.double(reference$code))
    expect_identical(names(labels)[match(as.double(result), unname(labels))],
        as.character(reference$label_text))
})

test_that("Unicode descriptions follow the measured group width contract", {
    reference <- read_dta(fixture("egen_unicode_names_stata18.dta"))
    columns <- as.list(reference)[seq_len(3L)]
    for (kind in c("group", "tag")) {
        helper <- if (kind == "group") dta_group_id else dta_group_tag
        result <- do.call(helper, columns)
        expected <- reference[[paste0(kind, "_unicode")]]
        # Tags intentionally use the same long-description rule as groups.
        # Stata's tag ado instead overwrites its 'see notes' label.
        expected_label <- if (kind == "tag") "see notes" else
            attr(expected, "label", exact = TRUE)
        expect_identical(attr(result, "label", exact = TRUE),
            expected_label)
        expect_identical(attr(result, "notes", exact = TRUE),
            attr(expected, "notes", exact = TRUE))
    }
    cases <- list(tag_byte_width = 6L, tag_ascii_long = 8:10)
    for (name in names(cases)) {
        result <- do.call(dta_group_tag, as.list(reference)[cases[[name]]])
        expected <- reference[[name]]
        narrow <- identical(name, "tag_byte_width")
        expect_identical(attr(result, "label", exact = TRUE),
            if (narrow) attr(expected, "label", exact = TRUE) else "see notes")
        expect_identical(attr(result, "notes", exact = TRUE),
            if (narrow) NULL else attr(expected, "notes", exact = TRUE))
    }
})
