# Generated by conformance/stata/summarize/summarize.do with Stata 18.0.
# Expectations include r() scalar presence as well as values. In particular,
# negative iweights and weights outside the selected sample follow Stata.
summarize_stata_fixture <- function(name) {
    raw <- read.csv(fixture(name), colClasses = "character",
        check.names = FALSE, na.strings = NULL, encoding = "UTF-8")
    character_columns <- c("case", "weight", "mode", "returned")
    for (name in setdiff(names(raw), character_columns)) {
        values <- raw[[name]]
        converted <- suppressWarnings(as.double(values))
        for (tag in letters) {
            converted[values == paste0(".", tag)] <- tagged_missing(tag)
        }
        raw[[name]] <- converted
    }
    raw
}

summarize_stata_call <- function(sample, weight, mode) {
    data <- dibble(x = dta_double(sample$x), w = dta_double(sample$w),
        selected = sample$selected)
    detail <- identical(mode, "detail")
    meanonly <- identical(mode, "meanonly")
    if (identical(weight, "none")) {
        summarize(data, x, where = selected == 1,
            detail = detail, meanonly = meanonly)
    } else {
        summarize(data, x, where = selected == 1, weights = w,
            weight = weight, detail = detail, meanonly = meanonly)
    }
}

expect_summarize_stata_scalar <- function(actual, expected, info) {
    # Relative error must still be checked for very small moments.
    # A plain absolute tolerance would accept zero for 1e-200.
    if (is.finite(expected) && expected != 0) {
        expect_equal(actual / expected, 1, tolerance = 1e-12, info = info)
    } else {
        expect_equal(actual, expected, tolerance = 1e-12, info = info)
    }
}

test_that("summarize scalars and weight validation match native Stata", {
    inputs <- summarize_stata_fixture("summarize_stata18_input.csv")
    reference <- summarize_stata_fixture("summarize_stata18.csv")
    scalar_names <- setdiff(names(reference),
        c("case", "weight", "mode", "rc", "returned"))
    expect_equal(nrow(reference), 420L)
    expect_setequal(unique(reference$rc), c(0, 101, 401, 402))
    for (i in seq_len(nrow(reference))) {
        expected <- reference[i, , drop = FALSE]
        sample <- inputs[inputs$case == expected$case, , drop = FALSE]
        info <- paste(expected$case, expected$weight, expected$mode)
        if (expected$rc != 0) {
            expect_error(summarize_stata_call(sample,
                expected$weight, expected$mode), info = info)
            next
        }
        result <- summarize_stata_call(sample,
            expected$weight, expected$mode)
        expect_equal(nrow(result$statistics), 1L, info = info)
        expect_identical(result$statistics$variable, "x", info = info)
        returned <- strsplit(expected$returned, " ", fixed = TRUE)[[1L]]
        expect_identical(sort(names(result$r)), sort(returned), info = info)
        for (name in returned) {
            expect_summarize_stata_scalar(result$r[[name]], expected[[name]],
                info = paste(info, "r()", name))
        }
        for (name in intersect(scalar_names, names(result$statistics))) {
            expect_summarize_stata_scalar(result$statistics[[name]], expected[[name]],
                info = paste(info, "statistics", name))
        }
    }
})

test_that("detail extremes use original rows with frequency weights", {
    # Native Stata displays 1, 2, 10, . as Smallest and ., 1, 2, 10
    # as Largest, even though fweights represent six observations.
    data <- dibble(x = c(1, 2, 10), w = c(1, 2, 3))
    result <- summarize(data, x, weights = w, weight = "fweight",
        detail = TRUE)
    expect_equal(result$smallest[[1L]], c(1, 2, 10, NA_real_))
    expect_equal(result$largest[[1L]], c(NA_real_, 1, 2, 10))
    expect_equal(result$r$N, 6)
    expect_equal(result$r$p50, 6)
})

test_that("native percentile boundary tolerance preserves weight intervals", {
    # Native Stata 18 returns 2.5 despite the different binary roundings of
    # cumulative .2 + .1 and total .4 * .75.
    expect_equal(summarize(1:3, weights = c(.2, .1, .1),
        detail = TRUE)$r$p75, 2.5)
    for (scale in c(1, 1e-100, 1e100)) {
        for (shift in c(-5e-8, 5e-8)) {
            result <- summarize(1:2,
                weights = c(.5 + shift, .5 - shift) * scale, detail = TRUE)
            expect_equal(result$r$p50, 1.5)
        }
        expect_equal(summarize(1:2,
            weights = c(.5 + 2e-7, .5 - 2e-7) * scale,
            detail = TRUE)$r$p50, 1)
        expect_equal(summarize(1:2,
            weights = c(.5 - 2e-7, .5 + 2e-7) * scale,
            detail = TRUE)$r$p50, 2)
    }
    # The tolerance also applies to frequency weights. A small observation
    # containing the target must still be retained when both edges are near.
    for (weight in c("aweight", "fweight")) {
        expect_equal(summarize(1:2, weights = c(50000001, 49999999),
            weight = weight, detail = TRUE)$r$p50, 1.5)
        expect_equal(summarize(1:3, weights = c(1e16, 3, 1e16),
            weight = weight, detail = TRUE)$r$p50, 2)
        expect_equal(summarize(1:3, weights = c(1e16, 1, 1e16),
            weight = weight, detail = TRUE)$r$p50, 1.5)
    }
})

test_that("overflowing weight totals preserve native unavailable statistics", {
    for (weight in c("aweight", "fweight")) {
        for (mode in c("default", "detail", "meanonly")) {
            result <- summarize(1:100, weights = rep(1e307, 100),
                weight = weight, detail = mode == "detail",
                meanonly = mode == "meanonly")
            expect_equal(result$r$N,
                if (weight == "fweight") NA_real_ else 100)
            unavailable <- intersect(c("sum_w", "sum", "mean", "Var", "sd",
                "skewness", "kurtosis"), names(result$r))
            expect_true(all(is.na(unlist(result$r[unavailable]))))
            expect_equal(result$r$min, 1)
            expect_equal(result$r$max, 100)
            if (mode == "detail") {
                # Native summarize leaves zero percentiles on total overflow.
                percentiles <- paste0("p", c(1, 5, 10, 25, 50, 75, 90, 95, 99))
                expect_equal(unname(unlist(result$r[percentiles])), rep(0, 9))
                expect_equal(result$smallest[[1L]], 1:4)
                expect_equal(result$largest[[1L]], 97:100)
            }
        }
    }
})

test_that("empty and string summaries preserve native last-variable r()", {
    data <- dibble(x = c(1, 2, 3), s = c("a", "", "b"))
    for (mode in c("default", "detail", "meanonly")) {
        detail <- identical(mode, "detail")
        meanonly <- identical(mode, "meanonly")
        result <- summarize(data, x, s, detail = detail, meanonly = meanonly)
        expect_identical(result$statistics$variable, c("x", "s"))
        expect_equal(result$statistics$N, c(3, 0))
        expect_equal(result$r, list(N = 0, sum_w = 0, sum = 0))
        empty <- summarize(data, x, where = FALSE,
            detail = detail, meanonly = meanonly)
        expect_equal(empty$r, list(N = 0, sum_w = 0, sum = 0))
    }
})
