list(R = structure(list(platform = "aarch64-apple-darwin25.4.0", 
    arch = "aarch64", os = "darwin25.4.0", system = "aarch64, darwin25.4.0", 
    status = "", major = "4", minor = "6.1", year = "2026", month = "06", 
    day = "24", `svn rev` = "90187", language = "R", version.string = "R version 4.6.1 (2026-06-24)", 
    nickname = "Happy Hop"), class = "simple.list"), libraries = c("/private/tmp/dta-direct-stage7-validation/implementation/candidate-96b9c3c7-01/library", 
"/opt/homebrew/lib/R/4.6/site-library", "/opt/homebrew/Cellar/r/4.6.1/lib/R/library"
), package_path = "/private/tmp/dta-direct-stage7-validation/implementation/candidate-96b9c3c7-01/library/dtatools", 
    exports = 106L, provenance = list(format = 1L, source_sha = "96b9c3c72400a36b13ed0172748537102364f8ea", 
        source_tree = "88a529ea2015ea10b0b51a47f054bb4367b1c145", 
        archive_md5 = "7069eca1d78f9229341e1ac7e67662fe", files = c(DESCRIPTION = "a87e6b07f8a940b0daa9963ebd76df4b", 
        INDEX = "7daa4220094da4cc89d27d604f6b91d9", `Meta/Rd.rds` = "a3d5751314af2cc50b17811b558ac517", 
        `Meta/features.rds` = "5a2c0c5aa235e99869a36d050ea8ee24", 
        `Meta/hsearch.rds` = "5bb23b3930da8561dd1ad02aa0255963", 
        `Meta/links.rds` = "3332eac92972be6a839134e243295ae3", 
        `Meta/nsInfo.rds` = "a967b67c47365feb5b07e6c30e7f10bc", 
        `Meta/package.rds` = "ea98a4050c9bcab02cfdd521ffbee0dc", 
        NAMESPACE = "ddfda3f881b12ae95b01e91f7f5d509c", NEWS.md = "13634da1f76972374a71c939643b4fe0", 
        NOTICE = "809e490365159ed904b57c98e32f5d3f", `R/dtatools` = "d6c68f1fe41ced6e98a766a3757313da", 
        `R/dtatools.rdb` = "2343442d5a9e13244718ada7b578cf7f", 
        `R/dtatools.rdx` = "c92e37d9d2eb9c8c813963a554f9c193", 
        README.md = "bd6d67d4d16feb3e87cae1cad37c6672", `extdata/all_types.dta` = "6717e0923a661edce9eeedbd3b477f0a", 
        `extdata/all_types_v115.dta` = "806a8ebc47eb77cd72810850db8e5b58", 
        `extdata/all_types_v117.dta` = "2832de91d4f650e3a7587544c0f63620", 
        `extdata/all_types_v118.dta` = "3ad28108592743ab7fe08dbaec8e4e79", 
        `extdata/auto_v115.dta` = "7e0ae5dd7cbe1ff309d91fd3c45aae94", 
        `extdata/auto_v117.dta` = "3f2541c2c1625bc30eb9d6d76bc44e17", 
        `extdata/auto_v118.dta` = "2996ac77bd2dd17e5ba606afe44a2aeb", 
        `extdata/egen_labels_stata18.csv` = "7a3f979af350c993e3def9c6692a8ab9", 
        `extdata/egen_number_labels_stata18.csv` = "5925e70aff4578bdabdcfeaf386784ba", 
        `extdata/egen_number_labels_stata18.dta` = "264832fc2cf1b2e44d9973aec631debe", 
        `extdata/egen_precision_stata18.csv` = "9d2b170d733dd3cfcbe12585b82c26f6", 
        `extdata/egen_stata18.csv` = "a6d5968f1480b98368c6a457a2038d90", 
        `extdata/egen_unicode_names_stata18.dta` = "bafa1c021a86f2a3b238cad70df262e4", 
        `extdata/empty.dta` = "991870899170ab5671befa453ee04eef", 
        `extdata/empty_v115.dta` = "b621f94de308537e5c38cd3789576164", 
        `extdata/empty_v118.dta` = "5dc77db329ea09e0ad443d30cd626f61", 
        `extdata/missing_values.dta` = "27ae82a9e7d6741e3a250713a7ac5c2e", 
        `extdata/missing_values_v115.dta` = "cd034ac854d25344d41a9a5531654d3a", 
        `extdata/missing_values_v118.dta` = "1d26f750d53212e3db7918a8e66ccd39", 
        `extdata/strl_test.dta` = "48f8056edf4b09bf9a55c577d08332f7", 
        `extdata/strl_test_v118.dta` = "c2d3e6fb34702ebc1878c535eefb4d01", 
        `extdata/synthetic_v105.dta` = "caaca35843ccbd2d66dbdc21035e0819", 
        `extdata/synthetic_v108.dta` = "d5868e9de820582b7bfc9d5bcfc95d0f", 
        `extdata/synthetic_v110.dta` = "4933d68b004d75128fa15d01bf16cad1", 
        `extdata/synthetic_v111.dta` = "9ae4636c52e65c51c70d55bf2916bc28", 
        `extdata/value_labels.dta` = "07be902858f7a2de6ca3a22c48b3ea81", 
        `extdata/value_labels_v115.dta` = "85590a0ff9aec1e192f13c6b93744839", 
        `extdata/value_labels_v117.dta` = "ddae0e8aa9c48dadc5872b3d312c29f3", 
        `extdata/value_labels_v118.dta` = "99a9cbf7a19cbe190ff90ebab7c4c09f", 
        `extdata/wide.dta` = "e521bfcf22acf39caff59c7771cd9799", 
        `extdata/wide_v115.dta` = "24245404fc155316f4daff10a6bcbe9d", 
        `extdata/wide_v118.dta` = "f3ed0f7280e6f28259a6d6fda3989e48", 
        `help/AnIndex` = "c2cf85e344c038a9b5e9ae25defae055", 
        `help/aliases.rds` = "5ec37d59d8598e53e1a048eede2b2bb2", 
        `help/dtatools.rdb` = "f9fee591a8c45539c1d4aa967ebda7ca", 
        `help/dtatools.rdx` = "9fa947453ec1a5756ed69df7520e3b04", 
        `help/paths.rds` = "39643a05a0592b1c078ba78e35b0ddf0", 
        `html/00Index.html` = "c1bc6fb4e3fc4211e48defda3eab7514", 
        `html/R.css` = "ee41876c0116916bb04bcf4fe3e43d78", `libs/dtatools.so` = "d1e23bedbf54e0ed43a1ba064f495a64", 
        `raven/nse.toml` = "41b79b3db66e968b68d11319504dc69d"
        )), dll = "/private/tmp/dta-direct-stage7-validation/implementation/candidate-96b9c3c7-01/library/dtatools/libs/dtatools.so", 
    session = structure(list(R.version = list(platform = "aarch64-apple-darwin25.4.0", 
        arch = "aarch64", os = "darwin25.4.0", system = "aarch64, darwin25.4.0", 
        status = "", major = "4", minor = "6.1", year = "2026", 
        month = "06", day = "24", `svn rev` = "90187", language = "R", 
        version.string = "R version 4.6.1 (2026-06-24)", nickname = "Happy Hop"), 
        platform = "aarch64-apple-darwin25.4.0", locale = "C.UTF-8/C.UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8", 
        tzone = "America/New_York", tzcode_type = "internal", 
        running = "macOS Tahoe 26.6.2", RNGkind = c("Mersenne-Twister", 
        "Inversion", "Rejection"), basePkgs = c("stats", "graphics", 
        "grDevices", "utils", "datasets", "methods", "base"), 
        loadedOnly = list(dtatools = structure(list(Package = "dtatools", 
            Title = "Fast Reader and Writer for Stata DTA Files", 
            Version = "0.8.0", `Authors@R` = "c(\n    person(\"Jonathan\", \"Bearak\", role = c(\"aut\", \"cre\"),\n        email = \"jonathan@bearak.net\"),\n    person(\"dplyr authors\", role = \"cph\",\n        comment = \"Adapted selectors, grouping, expressions and row policies; see inst/NOTICE\"),\n    person(\"R Core Team\", role = \"cph\",\n        comment = \"Adapted base subsetting policy; see inst/NOTICE\"))", 
            Description = "Reads Stata DTA files into tibbles or data tables with a Rust parser, multicore\n    decoding, and compact in-memory representations for numeric and character\n    columns. Its read interface follows 'haven' while retaining dataset labels,\n    variable labels, display formats, value labels, temporal classes, and Stata\n    tagged missing values. It writes standalone Stata 18 and 19 datasets through\n    a streaming Rust writer. It also provides merges under Stata missing-code\n    identity, label-aware tabulation, and tag-preserving recoding.", 
            License = "GPL-3", URL = "https://github.com/jbearak/dta-parser", 
            BugReports = "https://github.com/jbearak/dta-parser/issues", 
            Encoding = "UTF-8", Depends = "R (>= 4.6.0)", Imports = "dplyr (>= 1.2.1), lifecycle (>= 1.0.5), pillar, readr (>=\n2.2.0), rlang (>= 1.0.0), stats, tibble, tidyselect, utils,\nvctrs", 
            Suggests = "arrow, bit64, callr, data.table (>= 1.18.2.1), httpuv,\npkgload, stringi (>= 1.5.3), testthat (>= 3.1.7), withr", 
            `Config/testthat/edition` = "3", SystemRequirements = "Cargo and Rust >= 1.98.0; on Windows, the Rust\ntarget matching R (x86_64-pc-windows-gnu for x86_64 R or\naarch64-pc-windows-gnullvm for aarch64 R)", 
            NeedsCompilation = "yes", Roxygen = "list(markdown = TRUE)", 
            `Config/roxygen2/version` = "8.1.0", Packaged = "2026-09-09 01:30:21 UTC; jmb", 
            Author = "Jonathan Bearak [aut, cre],\n  dplyr authors [cph] (Adapted selectors, grouping, expressions and row\n    policies; see inst/NOTICE),\n  R Core Team [cph] (Adapted base subsetting policy; see inst/NOTICE)", 
            Maintainer = "Jonathan Bearak <jonathan@bearak.net>", 
            Built = "R 4.6.1; aarch64-apple-darwin25.4.0; 2026-09-09 01:30:24 UTC; unix"), class = "packageDescription", file = "/private/tmp/dta-direct-stage7-validation/implementation/candidate-96b9c3c7-01/library/dtatools/Meta/package.rds"), 
            compiler = structure(list(Package = "compiler", Version = "4.6.1", 
                Priority = "base", Title = "The R Compiler Package", 
                Author = "Luke Tierney <luke-tierney@uiowa.edu>", 
                Maintainer = "R Core Team <do-use-Contact-address@r-project.org>", 
                Contact = "R-help mailing list <r-help@r-project.org>", 
                Description = "Byte code compiler for R.", License = "Part of R 4.6.1", 
                Built = "R 4.6.1; ; 2026-06-24 09:37:27 UTC; unix"), class = "packageDescription", file = "/opt/homebrew/Cellar/r/4.6.1/lib/R/library/compiler/Meta/package.rds"), 
            magrittr = structure(list(Type = "Package", Package = "magrittr", 
                Title = "A Forward-Pipe Operator for R", Version = "2.0.5", 
                `Authors@R` = "c(\n    person(\"Stefan Milton\", \"Bache\", , \"stefan@stefanbache.dk\", role = c(\"aut\", \"cph\"),\n           comment = \"Original author and creator of magrittr\"),\n    person(\"Hadley\", \"Wickham\", , \"hadley@posit.co\", role = \"aut\"),\n    person(\"Lionel\", \"Henry\", , \"lionel@posit.co\", role = \"cre\"),\n    person(\"Posit Software, PBC\", role = c(\"cph\", \"fnd\"),\n            comment = c(ROR = \"03wc8by49\"))\n  )", 
                Description = "Provides a mechanism for chaining commands with a new\n    forward-pipe operator, %>%. This operator will forward a value, or the\n    result of an expression, into the next function call/expression.\n    There is flexible support for the type of right-hand side expressions.\n    For more information, see package vignette.  To quote Rene Magritte,\n    \"Ceci n'est pas un pipe.\"", 
                License = "MIT + file LICENSE", URL = "https://magrittr.tidyverse.org,\nhttps://github.com/tidyverse/magrittr", 
                BugReports = "https://github.com/tidyverse/magrittr/issues", 
                Depends = "R (>= 3.4.0)", Suggests = "covr, knitr, rlang, rmarkdown, testthat", 
                VignetteBuilder = "knitr", ByteCompile = "Yes", 
                `Config/Needs/website` = "tidyverse/tidytemplate", 
                Encoding = "UTF-8", RoxygenNote = "7.3.3", NeedsCompilation = "yes", 
                Packaged = "2026-04-03 08:09:48 UTC; lionel", 
                Author = "Stefan Milton Bache [aut, cph] (Original author and creator of\n    magrittr),\n  Hadley Wickham [aut],\n  Lionel Henry [cre],\n  Posit Software, PBC [cph, fnd] (ROR: <https://ror.org/03wc8by49>)", 
                Maintainer = "Lionel Henry <lionel@posit.co>", 
                Repository = "CRAN", `Date/Publication` = "2026-04-04 08:00:02 UTC", 
                Built = "R 4.6.0; aarch64-apple-darwin25.4.0; 2026-04-29 20:22:22 UTC; unix", 
                RemoteType = "standard", RemotePkgRef = "magrittr", 
                RemoteRef = "magrittr", RemoteRepos = "https://cloud.r-project.org", 
                RemotePkgPlatform = "source", RemoteSha = "2.0.5"), class = "packageDescription", file = "/opt/homebrew/lib/R/4.6/site-library/magrittr/Meta/package.rds"), 
            cli = structure(list(Package = "cli", Title = "Helpers for Developing Command Line Interfaces", 
                Version = "3.6.6", `Authors@R` = "c(\n    person(\"Gábor\", \"Csárdi\", , \"gabor@posit.co\", role = c(\"aut\", \"cre\")),\n    person(\"Hadley\", \"Wickham\", role = \"ctb\"),\n    person(\"Kirill\", \"Müller\", role = \"ctb\"),\n    person(\"Salim\", \"Brüggemann\", , \"salim-b@pm.me\", role = \"ctb\",\n           comment = c(ORCID = \"0000-0002-5329-5987\")),\n    person(\"Posit Software, PBC\", role = c(\"cph\", \"fnd\"),\n           comment = c(ROR = \"03wc8by49\"))\n  )", 
                Description = "A suite of tools to build attractive command line interfaces\n    ('CLIs'), from semantic elements: headings, lists, alerts, paragraphs,\n    etc. Supports custom themes via a 'CSS'-like language. It also\n    contains a number of lower level 'CLI' elements: rules, boxes, trees,\n    and 'Unicode' symbols with 'ASCII' alternatives. It support ANSI\n    colors and text styles as well.", 
                License = "MIT + file LICENSE", URL = "https://cli.r-lib.org, https://github.com/r-lib/cli", 
                BugReports = "https://github.com/r-lib/cli/issues", 
                Depends = "R (>= 3.4)", Imports = "utils", Suggests = "callr, covr, crayon, digest, glue (>= 1.6.0), grDevices,\nhtmltools, htmlwidgets, knitr, methods, processx, ps (>=\n1.3.4.9000), rlang (>= 1.0.2.9003), rmarkdown, rprojroot,\nrstudioapi, testthat (>= 3.2.0), tibble, whoami, withr", 
                `Config/Needs/website` = "r-lib/asciicast, bench, brio, cpp11, decor, desc,\nfansi, prettyunits, sessioninfo, tidyverse/tidytemplate,\nusethis, vctrs", 
                `Config/testthat/edition` = "3", `Config/usethis/last-upkeep` = "2025-04-25", 
                Encoding = "UTF-8", RoxygenNote = "7.3.2.9000", 
                NeedsCompilation = "yes", Packaged = "2026-04-08 18:14:45 UTC; gaborcsardi", 
                Author = "Gábor Csárdi [aut, cre],\n  Hadley Wickham [ctb],\n  Kirill Müller [ctb],\n  Salim Brüggemann [ctb] (ORCID: <https://orcid.org/0000-0002-5329-5987>),\n  Posit Software, PBC [cph, fnd] (ROR: <https://ror.org/03wc8by49>)", 
                Maintainer = "Gábor Csárdi <gabor@posit.co>", 
                Repository = "CRAN", `Date/Publication` = "2026-04-09 09:50:18 UTC", 
                Built = "R 4.6.1; aarch64-apple-darwin25.4.0; 2026-07-21 00:13:57 UTC; unix", 
                RemoteType = "standard", RemoteRef = "cli", RemotePkgRef = "cli", 
                RemoteRepos = "https://cloud.r-project.org", 
                RemoteReposName = "CRAN", RemotePkgPlatform = "source", 
                RemoteSha = "3.6.6"), class = "packageDescription", file = "/opt/homebrew/lib/R/4.6/site-library/cli/Meta/package.rds"), 
            tools = structure(list(Package = "tools", Version = "4.6.1", 
                Priority = "base", Title = "Tools for Package Development", 
                Author = "R Core Team", Maintainer = "R Core Team <do-use-Contact-address@r-project.org>", 
                Contact = "R-help mailing list <r-help@r-project.org>", 
                Description = "Tools for package development, administration and documentation.", 
                License = "Part of R 4.6.1", Suggests = "codetools, methods, xml2, curl, commonmark, knitr, xfun, mathjaxr, V8, bibtex", 
                NeedsCompilation = "yes", Built = "R 4.6.1; aarch64-apple-darwin25.4.0; 2026-06-24 09:37:27 UTC; unix"), class = "packageDescription", file = "/opt/homebrew/Cellar/r/4.6.1/lib/R/library/tools/Meta/package.rds"), 
            pillar = structure(list(Package = "pillar", Title = "Coloured Formatting for Columns", 
                Version = "1.11.1", `Authors@R` = "\n    c(person(given = \"Kirill\",\n             family = \"M\\u00fcller\",\n             role = c(\"aut\", \"cre\"),\n             email = \"kirill@cynkra.com\",\n             comment = c(ORCID = \"0000-0002-1416-3412\")),\n      person(given = \"Hadley\",\n             family = \"Wickham\",\n             role = \"aut\"),\n      person(given = \"RStudio\",\n             role = \"cph\"))", 
                Description = "Provides 'pillar' and 'colonnade' generics designed\n    for formatting columns of data using the full range of colours\n    provided by modern terminals.", 
                License = "MIT + file LICENSE", URL = "https://pillar.r-lib.org/, https://github.com/r-lib/pillar", 
                BugReports = "https://github.com/r-lib/pillar/issues", 
                Imports = "cli (>= 2.3.0), glue, lifecycle, rlang (>= 1.0.2), utf8 (>=\n1.1.0), utils, vctrs (>= 0.5.0)", 
                Suggests = "bit64, DBI, debugme, DiagrammeR, dplyr, formattable, ggplot2,\nknitr, lubridate, nanotime, nycflights13, palmerpenguins,\nrmarkdown, scales, stringi, survival, testthat (>= 3.1.1),\ntibble, units (>= 0.7.2), vdiffr, withr", 
                VignetteBuilder = "knitr", Encoding = "UTF-8", 
                RoxygenNote = "7.3.3.9000", `Config/testthat/edition` = "3", 
                `Config/testthat/parallel` = "true", `Config/testthat/start-first` = "format_multi_fuzz, format_multi_fuzz_2,\nformat_multi, ctl_colonnade, ctl_colonnade_1, ctl_colonnade_2", 
                `Config/autostyle/scope` = "line_breaks", `Config/autostyle/strict` = "true", 
                `Config/gha/extra-packages` = "units=?ignore-before-r=4.3.0", 
                `Config/Needs/website` = "tidyverse/tidytemplate", 
                NeedsCompilation = "no", Packaged = "2025-09-17 03:59:12 UTC; kirill", 
                Author = "Kirill Müller [aut, cre] (ORCID:\n    <https://orcid.org/0000-0002-1416-3412>),\n  Hadley Wickham [aut],\n  RStudio [cph]", 
                Maintainer = "Kirill Müller <kirill@cynkra.com>", 
                Repository = "CRAN", `Date/Publication` = "2025-09-17 11:20:02 UTC", 
                Built = "R 4.6.0; ; 2026-04-29 20:22:29 UTC; unix", 
                RemoteType = "standard", RemotePkgRef = "pillar", 
                RemoteRef = "pillar", RemoteRepos = "https://cloud.r-project.org", 
                RemotePkgPlatform = "source", RemoteSha = "1.11.1"), class = "packageDescription", file = "/opt/homebrew/lib/R/4.6/site-library/pillar/Meta/package.rds"), 
            glue = structure(list(Package = "glue", Title = "Interpreted String Literals", 
                Version = "1.8.1", `Authors@R` = "c(\n    person(\"Jim\", \"Hester\", role = \"aut\",\n           comment = c(ORCID = \"0000-0002-2739-7082\")),\n    person(\"Jennifer\", \"Bryan\", , \"jenny@posit.co\", role = c(\"aut\", \"cre\"),\n           comment = c(ORCID = \"0000-0002-6983-2759\")),\n    person(\"Posit Software, PBC\", role = c(\"cph\", \"fnd\"),\n           comment = c(ROR = \"03wc8by49\"))\n  )", 
                Description = "An implementation of interpreted string literals, inspired by\n    Python's Literal String Interpolation\n    <https://www.python.org/dev/peps/pep-0498/> and Docstrings\n    <https://www.python.org/dev/peps/pep-0257/> and Julia's Triple-Quoted\n    String Literals\n    <https://docs.julialang.org/en/v1.3/manual/strings/#Triple-Quoted-String-Literals-1>.", 
                License = "MIT + file LICENSE", URL = "https://glue.tidyverse.org/, https://github.com/tidyverse/glue", 
                BugReports = "https://github.com/tidyverse/glue/issues", 
                Depends = "R (>= 4.1)", Imports = "methods", 
                Suggests = "crayon, DBI (>= 1.2.0), dplyr, knitr, rlang, rmarkdown,\nRSQLite, testthat (>= 3.2.0), vctrs (>= 0.3.0), waldo (>=\n0.5.3), withr", 
                VignetteBuilder = "knitr", ByteCompile = "true", 
                `Config/Needs/website` = "bench, forcats, ggbeeswarm, ggplot2, R.utils,\nrprintf, tidyr, tidyverse/tidytemplate", 
                `Config/testthat/edition` = "3", `Config/usethis/last-upkeep` = "2026-04-16", 
                Encoding = "UTF-8", RoxygenNote = "7.3.3", NeedsCompilation = "yes", 
                Packaged = "2026-04-16 22:53:02 UTC; jenny", 
                Author = "Jim Hester [aut] (ORCID: <https://orcid.org/0000-0002-2739-7082>),\n  Jennifer Bryan [aut, cre] (ORCID:\n    <https://orcid.org/0000-0002-6983-2759>),\n  Posit Software, PBC [cph, fnd] (ROR: <https://ror.org/03wc8by49>)", 
                Maintainer = "Jennifer Bryan <jenny@posit.co>", 
                Repository = "CRAN", `Date/Publication` = "2026-04-17 05:11:01 UTC", 
                Built = "R 4.6.0; aarch64-apple-darwin25.4.0; 2026-04-29 20:22:05 UTC; unix", 
                RemoteType = "standard", RemotePkgRef = "glue", 
                RemoteRef = "glue", RemoteRepos = "https://cloud.r-project.org", 
                RemotePkgPlatform = "source", RemoteSha = "1.8.1"), class = "packageDescription", file = "/opt/homebrew/lib/R/4.6/site-library/glue/Meta/package.rds"), 
            tibble = structure(list(Package = "tibble", Title = "Simple Data Frames", 
                Version = "3.3.1", `Authors@R` = "c(\n    person(\"Kirill\", \"Müller\", , \"kirill@cynkra.com\", role = c(\"aut\", \"cre\"),\n           comment = c(ORCID = \"0000-0002-1416-3412\")),\n    person(\"Hadley\", \"Wickham\", , \"hadley@rstudio.com\", role = \"aut\"),\n    person(\"Romain\", \"Francois\", , \"romain@r-enthusiasts.com\", role = \"ctb\"),\n    person(\"Jennifer\", \"Bryan\", , \"jenny@rstudio.com\", role = \"ctb\"),\n    person(\"Posit Software, PBC\", role = c(\"cph\", \"fnd\"),\n           comment = c(ROR = \"03wc8by49\"))\n  )", 
                Description = "Provides a 'tbl_df' class (the 'tibble') with stricter\n    checking and better formatting than the traditional data frame.", 
                License = "MIT + file LICENSE", URL = "https://tibble.tidyverse.org/, https://github.com/tidyverse/tibble", 
                BugReports = "https://github.com/tidyverse/tibble/issues", 
                Depends = "R (>= 3.4.0)", Imports = "cli, lifecycle (>= 1.0.0), magrittr, methods, pillar (>=\n1.8.1), pkgconfig, rlang (>= 1.0.2), utils, vctrs (>= 0.5.0)", 
                Suggests = "bench, bit64, blob, brio, callr, DiagrammeR, dplyr, evaluate,\nformattable, ggplot2, here, hms, htmltools, knitr, lubridate,\nnycflights13, pkgload, purrr, rmarkdown, stringi, testthat (>=\n3.0.2), tidyr, withr", 
                VignetteBuilder = "knitr", `Config/autostyle/rmd` = "false", 
                `Config/autostyle/scope` = "line_breaks", `Config/autostyle/strict` = "true", 
                `Config/Needs/website` = "tidyverse/tidytemplate", 
                `Config/testthat/edition` = "3", `Config/testthat/parallel` = "true", 
                `Config/testthat/start-first` = "vignette-formats, as_tibble, add,\ninvariants", 
                `Config/usethis/last-upkeep` = "2025-06-07", 
                Encoding = "UTF-8", RoxygenNote = "7.3.3.9000", 
                NeedsCompilation = "yes", Packaged = "2026-01-10 18:28:47 UTC; kirill", 
                Author = "Kirill Müller [aut, cre] (ORCID:\n    <https://orcid.org/0000-0002-1416-3412>),\n  Hadley Wickham [aut],\n  Romain Francois [ctb],\n  Jennifer Bryan [ctb],\n  Posit Software, PBC [cph, fnd] (ROR: <https://ror.org/03wc8by49>)", 
                Maintainer = "Kirill Müller <kirill@cynkra.com>", 
                Repository = "CRAN", `Date/Publication` = "2026-01-11 10:10:02 UTC", 
                Built = "R 4.6.0; aarch64-apple-darwin25.4.0; 2026-04-29 20:22:31 UTC; unix", 
                RemoteType = "standard", RemotePkgRef = "tibble", 
                RemoteRef = "tibble", RemoteRepos = "https://cloud.r-project.org", 
                RemotePkgPlatform = "source", RemoteSha = "3.3.1"), class = "packageDescription", file = "/opt/homebrew/lib/R/4.6/site-library/tibble/Meta/package.rds"), 
            vctrs = structure(list(Package = "vctrs", Title = "Vector Helpers", 
                Version = "0.7.3", `Authors@R` = "c(\n    person(\"Hadley\", \"Wickham\", , \"hadley@posit.co\", role = \"aut\"),\n    person(\"Lionel\", \"Henry\", , \"lionel@posit.co\", role = \"aut\"),\n    person(\"Davis\", \"Vaughan\", , \"davis@posit.co\", role = c(\"aut\", \"cre\")),\n    person(\"data.table team\", role = \"cph\",\n           comment = \"Radix sort based on data.table's forder() and their contribution to R's order()\"),\n    person(\"Posit Software, PBC\", role = c(\"cph\", \"fnd\"))\n  )", 
                Description = "Defines new notions of prototype and size that are used to\n    provide tools for consistent and well-founded type-coercion and\n    size-recycling, and are in turn connected to ideas of type- and\n    size-stability useful for analysing function interfaces.", 
                License = "MIT + file LICENSE", URL = "https://vctrs.r-lib.org/, https://github.com/r-lib/vctrs", 
                BugReports = "https://github.com/r-lib/vctrs/issues", 
                Depends = "R (>= 4.0.0)", Imports = "cli (>= 3.4.0), glue, lifecycle (>= 1.0.3), rlang (>= 1.1.7)", 
                Suggests = "bit64, covr, crayon, dplyr (>= 0.8.5), generics, knitr,\npillar (>= 1.4.4), pkgdown (>= 2.0.1), rmarkdown, testthat (>=\n3.0.0), tibble (>= 3.1.3), waldo (>= 0.2.0), withr, xml2,\nzeallot", 
                VignetteBuilder = "knitr", `Config/build/compilation-database` = "true", 
                `Config/Needs/website` = "tidyverse/tidytemplate", 
                `Config/testthat/edition` = "3", `Config/testthat/parallel` = "true", 
                Encoding = "UTF-8", KeepSource = "true", Language = "en-GB", 
                RoxygenNote = "7.3.3", NeedsCompilation = "yes", 
                Packaged = "2026-04-10 14:27:17 UTC; davis", 
                Author = "Hadley Wickham [aut],\n  Lionel Henry [aut],\n  Davis Vaughan [aut, cre],\n  data.table team [cph] (Radix sort based on data.table's forder() and\n    their contribution to R's order()),\n  Posit Software, PBC [cph, fnd]", 
                Maintainer = "Davis Vaughan <davis@posit.co>", 
                Repository = "CRAN", `Date/Publication` = "2026-04-11 06:20:03 UTC", 
                Built = "R 4.6.0; aarch64-apple-darwin25.4.0; 2026-04-29 20:22:06 UTC; unix", 
                RemoteType = "standard", RemotePkgRef = "vctrs", 
                RemoteRef = "vctrs", RemoteRepos = "https://cloud.r-project.org", 
                RemotePkgPlatform = "source", RemoteSha = "0.7.3"), class = "packageDescription", file = "/opt/homebrew/lib/R/4.6/site-library/vctrs/Meta/package.rds"), 
            lifecycle = structure(list(Package = "lifecycle", 
                Title = "Manage the Life Cycle of your Package Functions", 
                Version = "1.0.5", `Authors@R` = "c(\n    person(\"Lionel\", \"Henry\", , \"lionel@posit.co\", role = c(\"aut\", \"cre\")),\n    person(\"Hadley\", \"Wickham\", , \"hadley@posit.co\", role = \"aut\",\n           comment = c(ORCID = \"0000-0003-4757-117X\")),\n    person(\"Posit Software, PBC\", role = c(\"cph\", \"fnd\"))\n  )", 
                Description = "Manage the life cycle of your exported functions with shared\n    conventions, documentation badges, and user-friendly deprecation\n    warnings.", 
                License = "MIT + file LICENSE", URL = "https://lifecycle.r-lib.org/, https://github.com/r-lib/lifecycle", 
                BugReports = "https://github.com/r-lib/lifecycle/issues", 
                Depends = "R (>= 3.6)", Imports = "cli (>= 3.4.0), rlang (>= 1.1.0)", 
                Suggests = "covr, knitr, lintr (>= 3.1.0), rmarkdown, testthat (>=\n3.0.1), tibble, tidyverse, tools, vctrs, withr, xml2", 
                VignetteBuilder = "knitr", `Config/Needs/website` = "tidyverse/tidytemplate, usethis", 
                `Config/testthat/edition` = "3", Encoding = "UTF-8", 
                RoxygenNote = "7.3.3", NeedsCompilation = "no", 
                Packaged = "2026-01-07 15:00:49 UTC; lionel", 
                Author = "Lionel Henry [aut, cre],\n  Hadley Wickham [aut] (ORCID: <https://orcid.org/0000-0003-4757-117X>),\n  Posit Software, PBC [cph, fnd]", 
                Maintainer = "Lionel Henry <lionel@posit.co>", 
                Repository = "CRAN", `Date/Publication` = "2026-01-08 08:00:02 UTC", 
                Built = "R 4.6.0; ; 2026-04-29 20:21:22 UTC; unix", 
                RemoteType = "standard", RemotePkgRef = "lifecycle", 
                RemoteRef = "lifecycle", RemoteRepos = "https://cloud.r-project.org", 
                RemotePkgPlatform = "source", RemoteSha = "1.0.5"), class = "packageDescription", file = "/opt/homebrew/lib/R/4.6/site-library/lifecycle/Meta/package.rds"), 
            pkgconfig = structure(list(Package = "pkgconfig", 
                Title = "Private Configuration for 'R' Packages", 
                Version = "2.0.3", Author = "Gábor Csárdi", 
                Maintainer = "Gábor Csárdi <csardi.gabor@gmail.com>", 
                Description = "Set configuration options on a per-package basis.\n    Options set by a given package only apply to that package,\n    other packages are unaffected.", 
                License = "MIT + file LICENSE", LazyData = "true", 
                Imports = "utils", Suggests = "covr, testthat, disposables (>= 1.0.3)", 
                URL = "https://github.com/r-lib/pkgconfig#readme", 
                BugReports = "https://github.com/r-lib/pkgconfig/issues", 
                Encoding = "UTF-8", NeedsCompilation = "no", 
                Packaged = "2019-09-22 08:42:40 UTC; gaborcsardi", 
                Repository = "CRAN", `Date/Publication` = "2019-09-22 09:20:02 UTC", 
                Built = "R 4.6.0; ; 2026-04-29 20:22:22 UTC; unix", 
                RemoteType = "standard", RemotePkgRef = "pkgconfig", 
                RemoteRef = "pkgconfig", RemoteRepos = "https://cloud.r-project.org", 
                RemotePkgPlatform = "source", RemoteSha = "2.0.3"), class = "packageDescription", file = "/opt/homebrew/lib/R/4.6/site-library/pkgconfig/Meta/package.rds"), 
            rlang = structure(list(Package = "rlang", Version = "1.3.0", 
                Title = "Functions for Base Types and Core R and 'Tidyverse' Features", 
                `Authors@R` = "c(\n    person(\"Lionel\", \"Henry\", , \"lionel@posit.co\", role = c(\"aut\", \"cre\")),\n    person(\"Hadley\", \"Wickham\", , \"hadley@posit.co\", role = \"aut\"),\n    person(\"mikefc\", , , \"mikefc@coolbutuseless.com\", role = \"cph\",\n           comment = \"Hash implementation based on Mike's xxhashlite\"),\n    person(\"Yann\", \"Collet\", role = \"cph\",\n           comment = \"Author of the embedded xxHash library\"),\n    person(\"Posit, PBC\", role = c(\"cph\", \"fnd\"))\n  )", 
                Description = "A toolbox for working with base types, core R features like\n    the condition system, and core 'Tidyverse' features like tidy\n    evaluation.", 
                License = "MIT + file LICENSE", URL = "https://rlang.r-lib.org, https://github.com/r-lib/rlang", 
                BugReports = "https://github.com/r-lib/rlang/issues", 
                Depends = "R (>= 4.0.0)", Imports = "utils", 
                Suggests = "cli (>= 3.1.0), covr, crayon, desc, fs, glue, knitr,\nmagrittr, methods, pillar, pkgload, rmarkdown, stats, testthat\n(>= 3.3.2), tibble, usethis, vctrs (>= 0.2.3), withr", 
                Enhances = "winch", Biarch = "true", ByteCompile = "true", 
                `Config/build/compilation-database` = "true", 
                `Config/Needs/website` = "dplyr, tidyverse/tidytemplate", 
                `Config/roxygen2/version` = "8.0.0", `Config/testthat/edition` = "3", 
                `Config/testthat/parallel` = "true", Encoding = "UTF-8", 
                NeedsCompilation = "yes", Packaged = "2026-07-01 15:54:09 UTC; lionel", 
                Author = "Lionel Henry [aut, cre],\n  Hadley Wickham [aut],\n  mikefc [cph] (Hash implementation based on Mike's xxhashlite),\n  Yann Collet [cph] (Author of the embedded xxHash library),\n  Posit, PBC [cph, fnd]", 
                Maintainer = "Lionel Henry <lionel@posit.co>", 
                Repository = "CRAN", `Date/Publication` = "2026-07-05 08:40:02 UTC", 
                Built = "R 4.6.1; aarch64-apple-darwin25.4.0; 2026-07-21 00:14:07 UTC; unix", 
                RemoteType = "standard", RemoteRef = "rlang", 
                RemotePkgRef = "rlang", RemoteRepos = "https://cloud.r-project.org", 
                RemoteReposName = "CRAN", RemotePkgPlatform = "source", 
                RemoteSha = "1.3.0"), class = "packageDescription", file = "/opt/homebrew/lib/R/4.6/site-library/rlang/Meta/package.rds")), 
        matprod = "default", BLAS = "/opt/homebrew/Cellar/openblas/0.3.34/lib/libopenblasp-r0.3.34.dylib", 
        LAPACK = "/opt/homebrew/Cellar/r/4.6.1/lib/R/lib/libRlapack.dylib", 
        LA_version = "3.12.1"), class = "sessionInfo"))
