[package]
name = "dtatools-r"
version = "0.6.0"
edition = "2021"
rust-version = "1.98.0"
license = "GPL-3.0-only"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
ahash = { version = "0.8", default-features = false, features = ["std"] }
arrow-array = "59.2.0"
arrow-buffer = "59.2.0"
arrow-schema = "59.2.0"
dta-tools = { path = "../dta-tools", features = ["r-adapter-internal"] }

[profile.release]
lto = "thin"
panic = "unwind"
strip = "debuginfo"

[workspace]
